package io.jmix.dependency.cli.gradle;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * Runs a Gradle task by invoking the workspace's generated Gradle <b>wrapper</b> as a subprocess.
 * <p>
 * v3 deliberately does NOT use the Gradle Tooling API: deptool only ever runs a task (it never fetches
 * Tooling models), and an embedded Tooling API would tie the tool to a single client version that cannot
 * span every framework line's Gradle (1.x->7.x, 2.x->8.x, 3.x->9.5). Driving the wrapper as a separate
 * process makes the daemon Gradle version whatever the wrapper's {@code distributionUrl} pins, decoupling
 * it from the tool entirely. The only requirement is that deptool's JVM can launch the daemon - JDK 17
 * covers Gradle 7.x through 9.x.
 */
public class JmixGradleClient {

    private static final Logger log = LoggerFactory.getLogger(JmixGradleClient.class);

    private static final boolean WINDOWS = System.getProperty("os.name").toLowerCase().startsWith("windows");

    private final Path projectDir;
    private final String gradleUserHomeDir;

    public JmixGradleClient(Path projectDir, String gradleUserHomeDir) {
        this.projectDir = projectDir;
        this.gradleUserHomeDir = gradleUserHomeDir;
    }

    /**
     * Runs a single task via the wrapper, streaming output to the console.
     * <p>
     * The {@link GradleArgs} project properties are written to {@code <projectDir>/gradle.properties} rather
     * than passed as {@code -P} on the command line; only raw arguments (and {@code --gradle-user-home},
     * {@code --console=plain}, {@code --no-daemon}) go on the command line. This keeps the command length
     * bounded no matter how many Jmix modules are resolved - the {@code jmixModules} list alone can hold
     * hundreds of coordinates with commercial add-ons, which would otherwise overflow the OS limit.
     */
    public void runTask(String taskName, GradleArgs args) {
        writeGradleProperties(args.properties());

        // Absolute wrapper path: the child process runs with its working directory set to the project dir,
        // so a relative gradlew path would resolve against that dir and fail ("system cannot find the path").
        Path dir = projectDir.toAbsolutePath().normalize();
        List<String> command = new ArrayList<>();
        if (WINDOWS) {
            command.add("cmd.exe");
            command.add("/c");
            command.add(dir.resolve("gradlew.bat").toString());
        } else {
            command.add(dir.resolve("gradlew").toString());
        }
        command.add(taskName);
        command.addAll(args.rawArgs());
        command.add("--gradle-user-home");
        // Absolute: Gradle resolves a relative --gradle-user-home against the daemon's working dir (the project
        // dir), which would land the cache somewhere `export` (run from a different dir) wouldn't find.
        command.add(Paths.get(gradleUserHomeDir).toAbsolutePath().normalize().toString());
        command.add("--console=plain");
        // One-shot batch tool: no lingering daemon to hold locks on the gradle-user-home that
        // `export` later walks, and re-runs with a different home are safe.
        command.add("--no-daemon");

        log.info("Running: {}", String.join(" ", command));

        ProcessBuilder builder = new ProcessBuilder(command)
                .directory(dir.toFile())
                .inheritIO();

        int exitCode;
        try {
            Process process = builder.start();
            exitCode = process.waitFor();
        } catch (IOException e) {
            throw new RuntimeException("Failed to start Gradle wrapper in " + projectDir, e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Gradle task '" + taskName + "' was interrupted", e);
        }

        if (exitCode != 0) {
            throw new RuntimeException("Gradle task '" + taskName + "' failed with exit code " + exitCode);
        }
    }

    /**
     * Writes the project properties to {@code <projectDir>/gradle.properties}, which Gradle auto-loads before
     * evaluating the build. Uses {@link Properties#store} so values (URLs with '{@code :}', credentials, etc.)
     * are escaped and round-trip exactly. Values are not logged - {@code jmixLicenseKey} is among them.
     */
    private void writeGradleProperties(Map<String, String> properties) {
        Path file = projectDir.resolve("gradle.properties");
        Properties props = new Properties();
        props.putAll(properties);
        try (OutputStream os = Files.newOutputStream(file)) {
            props.store(os, "Generated by deptool - resolution project properties");
        } catch (IOException e) {
            throw new RuntimeException("Unable to write gradle.properties to " + projectDir, e);
        }
        log.info("Wrote {} project propert{} to {}", properties.size(), properties.size() == 1 ? "y" : "ies", file);
    }
}
